// https://developer.android.com/jetpack/compose/performance/stability/fix#configuration-file

// Kotlin Immutable Collections
kotlinx.collections.immutable.*

kotlin.uuid.*
kotlin.time.*

// Java Time
java.time.*

com.sevensoft.weishu.data.model.Conversation
com.sevensoft.weishu.data.model.MessageNode
com.sevensoft.weishu.ai.ui.UIMessage
com.sevensoft.weishu.ai.ui.UIMessageChoice
com.sevensoft.weishu.ai.ui.MessageChunk
com.sevensoft.weishu.ai.ui.UIMessageAnnotation
com.sevensoft.weishu.ai.ui.ToolApprovalState
com.sevensoft.weishu.ai.core.TokenUsage